<h1>
    1. Tensor(텐서)
</h1>
텐서는(tensor)는 배열(array)이나 행렬(matrix)과 매우 유사란 특수한 자료구조입니다. pytorch에서는 텐서를 사용하여 모델의 입력과 출력뿐만 아니라 모델의 매개변수를 부호화 합니다.<br><br>
GPU나 다른 연산 가속을 위한 특수한 하드웨어에서 실행할 수 있다는 점을 제외하면, 텐서는 NumPy의 ndarray와 매우 유사합니다. 만약 ndarray에 익숙하다면 tensor API를 바로 사용할 수 있습니다. 만약 그렇지 않다면, 이 튜토리얼을 따라하며 API를 빠르게 익혀볼 수 있습니다.

In [2]:
import torch as tc
import numpy as np

<h3>
    1-1. Tensor초기화하기
</h3>
텐서는 여러가지 방법으로 초기화할 수 잇습니다. 다음 예를 살펴보자. <br><br>
<strong> 데이터로부터 직접생성하기</strong>
&nbsp; 데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 data type은 자동으로 유추합니다.

In [9]:
data = [[1,2],[3,4]]
x_data = tc.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


<strong>Numpy 배열로부터 생성하기</strong>
&nbsp; 텐서는 Numpy 배열로 생성할 수 있습니다.(그 반대도 가능)

In [6]:
np_array = np.array(data)
x_np = tc.tensor(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


<strong>다른 텐서로부터 생성하기</strong>
&nbsp; 명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape),자료형(datatype))을 유지합니다.

In [12]:
x_one = tc.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_one}\n")

x_rand = tc.rand_like(x_data, dtype=tc.float) # x_data의 속성을 덮어씁니다.(shape은 유지하되, datatype속성을 바꿈)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
 tensor([[0.4192, 0.0215],
        [0.2511, 0.0019]]) 



<strong>무작위(random)또는 상수(constant)값을 사용하기</strong> &nbsp; shape은 텐서의 차원(dimension)을 나타내는 튜플로 아래함수들에서는 출력 텐서의 차원을 결정한다.

In [16]:
shape = (2,3)
rand_tensor = tc.rand(shape)
ones_tensor = tc.ones(shape)
zeros_tensor = tc.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}\n")

Random Tensor: 
 tensor([[0.0825, 0.2173, 0.9250],
        [0.6320, 0.1496, 0.4254]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



<h3>
    1-2. 텐서의 속성(Attribute)
</h3>

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

In [20]:
tensor = tc.rand(3,4)

print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")

Shape of tensor:torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on:cpu


<h3>
    1-3. 텐서 연산(operation)
</h3>

전치(transposing),인덱싱(indexing),슬라이싱(Slicing),수학계산, 선형대수, 임의 샘플링(random sampling)등이 있다.<br>
각 연산들은(일반적으로 cpu보다 빠른) GPU에서 실행할 수 있습니다.

In [21]:
if tc.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is stored on: {tensor.device}")

<strong>Numpy식의 표준 인덱싱과 슬라이싱</strong>

In [24]:
tensor = tc.ones(4,4)
tensor[:,1]=0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


<strong>텐서합치기</strong>&nbsp;torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다. torch.cat과 미묘하게 다른 텐서 결합연산인 torch.stack이 있다.

In [29]:
t1=tc.cat([tensor,tensor,tensor],dim=1) #dim=1은 가로로 dim=0은 세로로 결합
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


<strong>텐서곱하기</strong>

In [33]:
#요소별 곱(element-wise product)을 계산합니다.
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)}\n")

#다른 문법
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


<strong>두 텐서 간의 행렬 곱(marix multiplication)</strong>

In [36]:
print(f"tensor.matmul(tensor.T)\n {tensor.matmul(tensor.T)}\n")
#다른문법
print(f"tensor @ tensor\n {tensor @ tensor.T}") # tensor.T => transpose tensor 

tensor.matmul(tensor.T)
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


<strong>바꿔치기(in-place)연산</strong> &nbsp "\_" 접미사를 갖는 연산들을 바꿔치기연산입니다. 예를 들어: x.copy_()나 x.t_()는 x를 변경합니다.

In [37]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<h3>Bridge
    Numpy 변환(Bridge)
</h3>

CPU 상의 텐서와 Numpy배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

<strong>텐서를 Numpy배열로 변환하기</strong>

In [38]:
t = tc.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경사항이 Nump배열에 반영됩니다.

In [39]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


<strong>Numpy 배열을 텐서로 변환하기</strong>

In [42]:
n=np.ones(5)
t=tc.from_numpy(n)

np.add(n,1,out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [50]:
tc.rand(2,3)

tensor([[0.7189, 0.1088, 0.7734],
        [0.7823, 0.4994, 0.5248]])