In [8]:
'''
tensor는 행렬이나 배열과 매우 유사한 특수한 자료구조이다.
pytorch에서는 tensor를 사용하여 모델의 입력과 출력 그리고 모델의 매개변수들을 부호화한다.
'''
import torch
import numpy as np

In [11]:
'''
torsor 초기화
'''
# 1. 데이터로 부터 직접생성하기 / 데이터로부터 직접 텐서를 생성할 수 잇습니다. 데이터의 type은 자동으로 결정된다.
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [14]:
# 2. Numpy배열로부터 생성하기 / tensor는 Numpy배열로 생성할 수 있다.
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [16]:
# 3. 다른 tensor로부터 생성하기 / 명시적으로 재정의하지 않는다면, 인자로 주어진 텐서의 속성을 유지합니다.

In [26]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor : \n {x_ones}\n")

x_rand=torch.rand_like(x_data, dtype=torch.float) # x-data의 속서을 덮어씁니다.
print(f"Random Tensor : \n {x_rand} \n")

Ones Tensor : 
 tensor([[1, 1],
        [1, 1]])

Random Tensor : 
 tensor([[0.6580, 0.3976],
        [0.7194, 0.6359]]) 



In [30]:
'''
Tensor의 속성
텐서의 속성은 텐서의 모양 자료형 및 어느장치에 저장되는지를 나타냅니다.
'''

'\nTensor의 속성\n텐서의 속성은 텐서의 모양 자료형 및 어느장치에 저장되는지를 나타냅니다.\n'

In [44]:
tensor = torch.rand(3,4)
print(f"Shape of tensor : {tensor.shape}")
print(f"Datatype of tensor:{tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

Shape of tensor : torch.Size([3, 4])
Datatype of tensor:torch.float32
Device tensor is stored on : cpu


In [49]:
'''
tensor operation
전치(transposing),인덱싱(indexing),슬라이싱(slicing),수학계산, 선형대수, 임의 샘플링(random sampling)등 100가지 이상의 텐서 연산들은 일반적으로 cpu보다 빠른
GPU에서 실행할 수 있습니다. 기본적으로 텐서는 cpu에 생성됩니다. .to메소드를 사용하면 gpu로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는
것은 시간과 메모리 측면에서 비용이 많이 든다는 것을 기억하세요!
'''

'\ntensor operation\n전치(transposing),인덱싱(indexing),슬라이싱(slicing),수학계산, 선형대수, 임의 샘플링(random sampling)등 100가지 이상의 텐서 연산들은 일반적으로 cpu보다 빠른\nGPU에서 실행할 수 있습니다. 기본적으로 텐서는 cpu에 생성됩니다. .to메소드를 사용하면 gpu로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는\n것은 시간과 메모리 측면에서 비용이 많이 든다는 것을 기억하세요!\n'

In [54]:
# GPU가 존재하면 텐서를 이동합니다.
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [67]:
tensor = torch.ones(4,4)
print(tensor)
print("first row:", tensor[0])
print("first column", tensor[:,0])
print("last column", tensor[...,-1])
tensor[:,1]=0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row: tensor([1., 1., 1., 1.])
first column tensor([1., 1., 1., 1.])
last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [70]:
# 텐서 합치기 torch.cat을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다. torch.cat과 미요하게 다른 또 다른 텐서 결합 연산인 torch.stack도 참고 바람
# dim =0 : 아래위로 연결, dim=1 : 양옆으로 연결
t1= torch.cat([tensor,tensor, tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [79]:
# 산술연산
# 두 텐서 간의 형렬 곱(matrix multiplication)을 계산합니다. y1,y2,y3은 모두 같은 값을 갖습니다.
y1 = tensor@tensor.T
y2 = tensor.matmul(tensor.T)

y3= torch. rand_like(tensor)
torch.matmul(tensor, tensor.T,out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [83]:
# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1=tensor * tensor
z2=tensor.mul(tensor)

z3=torch.rand_like(tensor)
torch.mul(tensor,tensor,out=y3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [84]:
# 단일-요소(single-element)텐서 : 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하니인 텐서의 경우,item()을 사용하여 python 숫자 값으로 변환할 수 있습니다.

In [90]:
agg=tensor.sum() # type = tensor
agg_item = agg.item()
print(agg_item, type(agg_item))

<class 'torch.Tensor'>
12.0 <class 'float'>


In [92]:
# 바꿔치기(in-place)연산 연산결과를 피연산자(operand)에 저장하는 연산을바꿔치기 연산이라고 부르며, _접미사를 갖습니다. 예를들어:x,copy_(y)나x.t_()는 x를 변경한다.
print(tensor,"\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
